GET http://localhost:3000/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjksImVtYWlsIjoibmFkaXIyQGdtYWlsLmNvbSIsImlhdCI6MTc1NzUyMTAxOCwiZXhwIjoxNzU3NTI0NjE4LCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.ZyvhTb0YqHoeH_BZN_Rlvs3jy7-gEOKe8WqONtBHT2E