POST http://localhost:3000/users
Content-Type: application/json

{
  "firstName": "Nadir",
  "lastName": "Bakhsh",
  "email": "nadir2@gmail.com",
  "password": "N@123321"
}

POST http://localhost:3000/users/create-many
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjksImVtYWlsIjoibmFkaXIyQGdtYWlsLmNvbSIsImlhdCI6MTc1NjMwMTAwOCwiZXhwIjoxNzU2MzA0NjA4LCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.e-7odaOi4mlAPHLHvVm3-kXxsTi0oLYvgitbfnfvY58
{  
  "users": [
    {
     "firstName": "Ali",
     "lastName": "khan",
     "email": "ali10@gmail.com",
     "password": "N@123321"
  },
    {
     "firstName": "Khan",
     "lastName": "bahi",
     "email": "khan11@gmail.com",
     "password": "N@123321"
  }
] 
}