POST http://localhost:3000/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjksImVtYWlsIjoibmFkaXIyQGdtYWlsLmNvbSIsImlhdCI6MTc1NjgyMzY2MCwiZXhwIjoxNzU2ODI3MjYwLCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.Hucq7A7s3081RqMMUMASd_vBqk8HfTJ7pndcxaAA3Fk
{
  "title": "What's new with NestJS 1",
  "postType": "post",
  "slug": "new-with-nestjs-41",
  "status": "draft",
  "content": "test content",
  "schema": "{\r\n \"@context\": \"https:\/\/schema.org\",\r\n \"@type\": \"Person\"\r\n }",
  "featuredImageUrl": "http://localhost.com/images/image1.jpg",
  "publishOn": "2025-09-02T12:00:00Z",
  //"tags": ["nestjs", "typescript"],
  "metaOptions" : {
      "metaValue": "{\"sidebarEnabled\": true, \"footerActive\":true}"
    },
  "tags": [1]
}